version: '3.9'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: node-backend
    restart: always
    ports:
      - "3131:3131"
    environment:
      - MONGO_URI=mongodb://mongo:27017/participantsDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: flutter-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
